### ISSUE TITLE
sizeof isn't highlighted

### ISSUE THREAD

**Issue by Ermanhaut** [Southclaws/pawn-sublime-language#83] opened 2018-06-08 05:05 UTC
![sizeof](https://user-images.githubusercontent.com/35643196/41139797-5dbba7ac-6ac0-11e8-8a8a-1719675d24b0.png)

**Comment by ICJefferson** [comment] 2018-06-08 07:39
Does your code compile? Function highlights may change if you have a missing token somewhere (comma, function closing brackets, semicolons, ...).

If it compiles, does it highlight without the parentheses?
```C
sizeof cars_Array
```
It highlights for me in both cases (with and without the parentheses) and I cannot reproduce a faulty highlight case.

**Comment by Ermanhaut** [comment] 2018-06-09 08:21
Yes, my code is normal, since i installed the package, sizeof doesn't highlight.

**Comment by Ermanhaut** [comment] 2018-06-09 10:01
![image](https://user-images.githubusercontent.com/35643196/41190322-c0fee91c-6bb2-11e8-881a-e11fcd68cc56.png)

**Comment by Southclaws** [comment] 2018-06-09 11:02
This may be the colour theme you're using. Highlighting is separated into two parts: syntax annotation and colour assignment:

The highlighter will [mark `sizeof` as `meta.function.c`](https://github.com/Southclaws/pawn-sublime-language/blob/master/Pawn.tmLanguage#L163) which tells the syntax engine that token has a specific name, it does not do anything with colour.

After that, the highlighter will colour tokens in the editor based on the currently set theme, if the theme doesn't have a colour for `meta.function.c` or the colour for that is the same as a regular symbol (such as `query` or `(`) then it won't be coloured.

I'd say try some other themes with wider support for TextMate symbol annotations.

**Closed by Southclaws** 2018-06-09 11:02 UTC
